name: QC Preflight Checks

on:
  pull_request:
  workflow_dispatch:

jobs:
  preflight:
    name: Run QC Preflight Checks
    uses: qualcomm/qcom-reusable-workflows/.github/workflows/reusable-qcom-preflight-checks-orchestrator.yml@v2
    with:
      enable-semgrep-scan: true
      enable-dependency-review: false
      enable-repolinter-check: false
      enable-copyright-license-check: false
      enable-commit-email-check: false
      enable-commit-msg-check: false
    permissions:
      contents: read
      security-events: write